Dictionaries
khbminus/fastTyping pull request #42
Opened 2022-05-21 17:39 UTC by jegorpopow

2022-05-29 20:42 UTC, Hello-zoka requested changes

2022-05-29 20:42 UTC, Hello-zoka commented on client/src/sonicSocket.cpp
> +const char ip[] = "localhost";
не запушь в мастер такое)

2022-05-29 20:42 UTC, Hello-zoka commented on server/include/server.h
> +    std::unique_ptr<UserStorage> user_storage;
mistakes пока лежат на полочке?

2022-05-29 20:42 UTC, Hello-zoka commented on server/src/database.cpp
> +DictionariesStorage::DictionariesStorage() : db(Database::get_instance()) {
ну у тебя же отдельный файлик сделан для словарей. Раз уже разделил обертки не надо все в одном файлике писать, а то 3 структурки  с кучей методов в одном файле....

2022-05-29 20:48 UTC, jegorpopow commented on server/include/server.h
> +    std::unique_ptr<UserStorage> user_storage;
Это при мерже с обработкой ошибок сделаем

2022-05-29 21:08 UTC, Hello-zoka commented on server/include/database.h
> +    T get_column(std::string const &query, std::string const &column);
нельзя так с темплейтами, в этой ветке тоже поправить надо бы

2022-05-29 21:08 UTC, Hello-zoka commented on server/include/database.h
> +    std::string get_column(std::string const &query, std::string const &column);
Можно удалить смело

2022-05-30 08:29 UTC, khbminus commented on server/src/dictionaries.cpp
> +    boost::split(words, raw, boost::is_any_of(" \t\n\r"));
https://www.boost.org/doc/libs/1_79_0/doc/html/boost/algorithm/is_space.html

2022-05-30 08:32 UTC, khbminus commented on server/src/game.cpp
>      if (!body.contains("words") || !body["words"].is_array()) {
Кажется, что вот это уже тоже не нужно

2022-05-30 08:38 UTC, jegorpopow commented on server/include/database.h
> +    std::string get_column(std::string const &query, std::string const &column);
Done

2022-05-30 08:38 UTC, jegorpopow commented on server/include/database.h
> +    T get_column(std::string const &query, std::string const &column);
Done

2022-05-30 11:48 UTC, merged